export const FETCH_QUESTION = "FETCH_QUESTION";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const POST_QUESTION = "POST_QUESTION";
export const LOGIN_USER = "LOGIN_USER";
export const SIGN_UP_USER = "SIGN_UP_USER";
